### ISSUE TITLE
Location of rom

### ISSUE THREAD

**Issue by KOLANICH** [omnirom/android_packages_apps_OpenDelta#12]
It would be good to use the same rom with cyandelta and opendelta. Both cyandelta and opendelta store a path to rom in xml, but both of them fix it to default location: cyandelta fixes on launch, opendelta fixes on update.

**Comment by Entropy512** [comment]
We do not use Github for code submissions or issue tracking.

gerrit.omnirom.org for code submission
jira.omnirom.org for issue tracking
