### ISSUE TITLE
json.php

### ISSUE THREAD

**Issue by regalstreak** [omnirom/android_packages_apps_OpenDelta#25]
I would like to have the json.php source. Ive spent a lot of time finding how do i implement recursive file listing with json but i could not. Please help me. Thanks.

**Comment by maxwen** [comment]
https://larsjung.de/h5ai/

**Comment by regalstreak** [comment]
Im sorry to ask again but which file in there @maxwen

**Comment by maxwen** [comment]
Setup your local web server install h5ai and you will see it

**Comment by regalstreak** [comment]
I have h5ai set up still it does not show that
http://downloads.regalstreak.me

Please help me im stuck at this since ywsterday 😭😭
